name: Publish Development Build
on:
    push:
    
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
      - name: Build
        run: ./gradlew build
      - name: Publish Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: meteor-community-addon
          path: ./build/libs/*.jar
